version: "3.9"
services:
    web:
        build: .
        ports:
            - "8000:8080"
        depends_on:
            - db
    db:
        image: postgres
        environment:
            POSTGRES_USER: sa
            POSTGRES_PASSWORD: postgres
            ACCEPT_EULA: "Y"